import { Injectable, Logger, OnModuleInit } from '@nestjs/common';
import { HttpService } from '@nestjs/axios';
import { ConfigService } from '@nestjs/config';
import { firstValueFrom } from 'rxjs';
import { KafkaService, KAFKA_TOPICS } from '@org/kafka-client';
import { PrismaService } from './prisma.service';
import type {
  TradeConfirmedPayload,
  MarketSettledPayload,
  DepositCompletedPayload,
  WithdrawalCompletedPayload,
  MarketResolvedPayload,
} from '@org/types';

export interface FeedItem {
  id: string;
  userId: string;
  type: string;
  title: string;
  body: string;
  metadata: Record<string, unknown>;
  occurredAt: Date;
}

@Injectable()
export class FeedService implements OnModuleInit {
  private readonly logger = new Logger(FeedService.name);
  private readonly marketServiceUrl: string;

  constructor(
    private readonly kafka: KafkaService,
    config: ConfigService,
    private readonly http: HttpService,
    private readonly prisma: PrismaService,
  ) {
    this.marketServiceUrl = config.get('MARKET_SERVICE_URL', 'http://localhost:3003');
  }

  /**
   * Was an in-memory Map, capped at 50 per user — every service restart
   * (a deploy, a crash, even a routine redeploy) silently wiped every
   * user's entire activity history with no way to recover it. Now a real
   * row; `id` is generated by Prisma rather than passed in, since a couple
   * of callers used a non-unique composite string as an id which is fine
   * for a Map key but not for a real primary key.
   */
  private async addToFeed(item: Omit<FeedItem, 'id' | 'occurredAt'>) {
    try {
      await this.prisma.feedItem.create({
        data: {
          userId: item.userId,
          type: item.type,
          title: item.title,
          body: item.body,
          metadata: item.metadata as any,
        },
      });
    } catch (err: unknown) {
      const msg = err instanceof Error ? err.message : String(err);
      this.logger.error(`Failed to record feed item for user ${item.userId}: ${msg}`);
    }
  }

  async onModuleInit() {
    await this.kafka.subscribe<TradeConfirmedPayload>(
      'feed-trade-confirmed-group',
      [KAFKA_TOPICS.TRADING_TRADE_CONFIRMED],
      async (_topic, payload) => {
        await this.addToFeed({
          userId: payload.userId,
          type: 'TRADE_CONFIRMED',
          title: 'Trade Placed',
          body: `You bought ${payload.sharesCount} ${payload.outcome} shares on "${payload.marketTitle}" for KES ${payload.amountKes.toLocaleString()}`,
          metadata: {
            marketId: payload.marketId,
            outcome: payload.outcome,
            amountKes: payload.amountKes,
            // The activity page's summary line reads this exact field —
            // without it, every trade row read "undefined shares".
            sharesCount: payload.sharesCount,
          },
        });
      },
    );

    await this.kafka.subscribe<MarketSettledPayload>(
      'feed-settlement-group',
      [KAFKA_TOPICS.TRADING_MARKET_SETTLED],
      async (_topic, payload) => {
        const won = payload.outcome === payload.winningOutcome;
        await this.addToFeed({
          userId: payload.userId,
          type: 'MARKET_SETTLED',
          title: won ? 'You Won!' : 'Market Settled',
          body: won
            ? `KES ${payload.payoutKes.toLocaleString()} credited for "${payload.marketTitle}"`
            : `Market "${payload.marketTitle}" resolved as ${payload.winningOutcome}`,
          metadata: {
            marketId: payload.marketId,
            payoutKes: payload.payoutKes,
            outcome: payload.winningOutcome,
            sharesHeld: payload.sharesHeld,
            won,
          },
        });
      },
    );

    await this.kafka.subscribe<DepositCompletedPayload>(
      'feed-deposit-group',
      [KAFKA_TOPICS.PAYMENT_DEPOSIT_COMPLETED],
      async (_topic, payload) => {
        await this.addToFeed({
          userId: payload.userId,
          type: 'DEPOSIT_COMPLETED',
          title: 'Deposit Received',
          body: `KES ${payload.amountKes.toLocaleString()} deposited via M-Pesa`,
          metadata: {
            amountKes: payload.amountKes,
            mpesaReceiptNumber: payload.mpesaReceiptNumber,
          },
        });
      },
    );

    await this.kafka.subscribe<WithdrawalCompletedPayload>(
      'feed-withdrawal-group',
      [KAFKA_TOPICS.PAYMENT_WITHDRAWAL_COMPLETED],
      async (_topic, payload) => {
        await this.addToFeed({
          userId: payload.userId,
          type: 'WITHDRAWAL_COMPLETED',
          title: 'Withdrawal Sent',
          body: `KES ${payload.amountKes.toLocaleString()} sent to ${payload.phone} via M-Pesa`,
          metadata: { amountKes: payload.amountKes },
        });
      },
    );

    await this.kafka.subscribe<MarketResolvedPayload>(
      'feed-market-resolved-group',
      [KAFKA_TOPICS.MARKET_RESOLVED],
      async (_topic, payload) => {
        // Global event — could broadcast to all subscribers of this market
        // For now just log; WebSocket gateway handles the room broadcast
        this.logger.log(`Market resolved: ${payload.marketId} → ${payload.outcome}`);
      },
    );

    this.logger.log('Feed Kafka consumers registered');
  }

  async getUserFeed(userId: string, page: number, limit: number) {
    const skip = (page - 1) * limit;
    const [items, total] = await Promise.all([
      this.prisma.feedItem.findMany({
        where: { userId },
        orderBy: { occurredAt: 'desc' },
        skip,
        take: limit,
      }),
      this.prisma.feedItem.count({ where: { userId } }),
    ]);

    // Shaped to match the frontend's Paginated<ActivityItem> — {data, total}
    // with {type, marketId, payload, createdAt} per row — not this service's
    // internal FeedItem shape ({items, metadata, occurredAt}), which the
    // frontend never actually read.
    return {
      data: items.map((item) => {
        const metadata = item.metadata as Record<string, unknown>;
        return {
          type: item.type,
          marketId: typeof metadata.marketId === 'string' ? metadata.marketId : undefined,
          payload: { title: item.title, body: item.body, ...metadata },
          createdAt: item.occurredAt.toISOString(),
        };
      }),
      total,
      page,
      limit,
    };
  }

  async getDiscoveryFeed(page: number, limit: number) {
    // Proxy to market-service for active markets sorted by volume
    try {
      const response = await firstValueFrom(
        this.http.get<unknown>(`${this.marketServiceUrl}/api/markets`, {
          params: { status: 'ACTIVE', page, limit, sort: 'volume' },
        }),
      );
      return response.data;
    } catch (err: unknown) {
      const msg = err instanceof Error ? err.message : String(err);
      this.logger.error(`Failed to fetch discovery feed: ${msg}`);
      return { data: [], meta: { total: 0, page, limit } };
    }
  }
}
